default_user:
  name: Pranay Automation Test
  first_name: Test
  last_name: Automation
  form_email: test.automation@gmail.com
  phone: "646 9564572"
  partner_name: Test Partner
  partner_email: test.partenerautomation@gmail.com
  address_line1: "50 West Washington Street"
  city: "Chicago"
  state: "Illinois"
  zip_code: "60602"
  country: "United States"

  email: ""  # Empty, email will be generated dynamically

